# Generated by Django 5.2.8 on 2026-02-04 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_idcard_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayorspermit',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='business_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='control_no',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='issue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='mayor',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='or_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='quarter',
            field=models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter')], db_index=True, default='First Quarter', max_length=100),
        ),
        migrations.AlterField(
            model_name='mayorspermit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], db_index=True, default='active', max_length=8),
        ),
    ]
