# Generated by Django 5.2.8 on 2025-11-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorspermit',
            name='quarter',
            field=models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter')], default='First Quarter', max_length=100),
        ),
    ]
