# Generated by Django 5.2.8 on 2025-11-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_mayorspermit_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorspermit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=8),
        ),
    ]
