# Generated by Django 5.2.8 on 2026-02-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mayorspermit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('make_kind', models.CharField(max_length=100)),
                ('engine_motor_no', models.CharField(max_length=100)),
                ('chassis_no', models.CharField(max_length=100)),
                ('plate_no', models.CharField(max_length=20, unique=True)),
                ('date_registered', models.DateField()),
                ('date_expired', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
