# Generated by Django 5.2.8 on 2025-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mayorspermit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mtop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('case_no', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('no_of_units', models.PositiveIntegerField()),
                ('route_operation', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=100)),
                ('motor_no', models.CharField(max_length=100, unique=True)),
                ('chasses_no', models.CharField(max_length=100, unique=True)),
                ('plate_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('municipal_treasurer', models.CharField(max_length=255)),
                ('officer_in_charge', models.CharField(max_length=255)),
                ('mayor', models.CharField(max_length=255)),
            ],
        ),
    ]
