# Generated by Django 5.2.8 on 2025-12-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mtop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('denomination', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_no', models.CharField(max_length=50)),
                ('valid_until', models.DateField()),
                ('motor_no', models.CharField(max_length=100)),
                ('authorized_no', models.CharField(max_length=50)),
                ('chassis_no', models.CharField(max_length=100)),
                ('authorized_route', models.TextField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('official_receipt_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('municipal_treasurer', models.CharField(max_length=255)),
            ],
        ),
    ]
