# Generated by Django 5.2.8 on 2025-12-04 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='MayorsPermitTricycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('motorized_operation', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('amount_paid', models.IntegerField()),
                ('or_no', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_at', models.CharField(max_length=255)),
                ('mayor', models.CharField(max_length=255)),
                ('quarter', models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter')], default='First Quarter', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=8)),
            ],
            options={
                'verbose_name': "Mayor's Permit - Tricycle",
                'verbose_name_plural': "Mayor's Permits - Tricycles",
            },
        ),
    ]
