# Generated by Django 5.2.8 on 2026-02-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_activitylog_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayorspermittricycle',
            name='tricycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mayors_permits', to='myapp.tricycle', to_field='body_number'),
        ),
    ]
