# Generated by Django 5.2.8 on 2026-02-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mayorspermittricycle_tricycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mayorspermittricycle',
            name='tricycle',
        ),
    ]
