# Generated by Django 5.2.8 on 2025-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_adminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='admins', to='myapp.adminpermission'),
        ),
    ]
