# Generated by Django 5.2.8 on 2025-12-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_admin_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='AdminPermission',
        ),
    ]
