# Generated by Django 5.2.8 on 2025-12-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_admin_permissions_delete_adminpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_view', models.BooleanField(default=False)),
                ('admin_view', models.BooleanField(default=False)),
                ('admin_add', models.BooleanField(default=False)),
                ('admin_edit', models.BooleanField(default=False)),
                ('admin_delete', models.BooleanField(default=False)),
                ('potpot_access', models.BooleanField(default=False)),
                ('mayors_permit_pedicab', models.BooleanField(default=False)),
                ('id_cards', models.BooleanField(default=False)),
                ('motorcycle_access', models.BooleanField(default=False)),
                ('mayors_permit_tricycle', models.BooleanField(default=False)),
                ('mtop', models.BooleanField(default=False)),
                ('franchise', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='myapp.admin')),
            ],
        ),
    ]
