# Generated by Django 5.2.8 on 2026-03-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_tricycle_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('potpot_admin', 'Potpot Admin'), ('tricycle_admin', 'Tricycle Admin'), ('both', 'Both')], default='potpot_admin', max_length=20),
        ),
        migrations.DeleteModel(
            name='AdminPermission',
        ),
    ]
