# Generated by Django 5.2.8 on 2025-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_adminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='permissions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='AdminPermission',
        ),
    ]
