# Generated by Django 5.2.8 on 2025-12-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_admin_permissions_delete_adminpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='permissions',
        ),
    ]
