# Generated by Django 5.2.8 on 2026-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_tricycle_toda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tricycle',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
