# Generated by Django 5.2.8 on 2025-12-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_admin_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPermission',
        ),
    ]
