# Generated by Django 5.2.8 on 2026-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_mayorspermittricycle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal'), ('Renewed', 'Renewed'), ('Expired', 'Expired'), ('Inactive', 'Inactive')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal'), ('Renewed', 'Renewed'), ('Expired', 'Expired'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
