# Generated by Django 5.2.8 on 2026-06-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_franchise_status_alter_tricycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
