# Generated by Django 5.2.8 on 2026-01-13 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_mayorspermithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MayorsPermitTricycleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=8)),
                ('new_status', models.CharField(max_length=8)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='myapp.mayorspermittricycle')),
            ],
        ),
    ]
