# Generated by Django 5.2.8 on 2026-01-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_mayorspermittricyclehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayorspermithistory',
            options={'ordering': ['-activated_at'], 'verbose_name': "Mayor's Permit History", 'verbose_name_plural': "Mayor's Permit Histories"},
        ),
        migrations.AddField(
            model_name='mayorspermithistory',
            name='updated_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mayorspermithistory',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mayorspermithistory',
            name='updated_by_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
