# Generated by Django 5.2.8 on 2026-01-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_mayorspermithistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayorspermittricyclehistory',
            options={'ordering': ['-activated_at'], 'verbose_name': 'Tricycle Permit History', 'verbose_name_plural': 'Tricycle Permit Histories'},
        ),
        migrations.AddField(
            model_name='mayorspermittricyclehistory',
            name='updated_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mayorspermittricyclehistory',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mayorspermittricyclehistory',
            name='updated_by_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
