# Generated by Django 5.2.8 on 2026-06-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_mayorspermit_created_at_mayorspermit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tricycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tricycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
