# Generated by Django 5.2.8 on 2026-06-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_tricycle_created_at_tricycle_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayorspermittricycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mayorspermittricycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
