# Generated by Django 5.2.8 on 2026-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_mayorspermittricyclehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Changed')], max_length=20)),
                ('model_type', models.CharField(choices=[('potpot', 'Potpot Permit'), ('motorcycle', 'Motorcycle Permit'), ('admin', 'Admin'), ('idcard', 'ID Card'), ('mtop', 'MTOP'), ('franchise', 'Franchise')], max_length=20)),
                ('object_id', models.CharField(max_length=100)),
                ('object_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
