# Generated by Django 5.2.8 on 2026-01-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
