# Generated by Django 5.2.8 on 2026-06-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_mayorspermittricycle_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mtop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
