# Generated by Django 5.2.8 on 2026-06-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_mtop_created_at_mtop_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
