# Generated by Django 5.2.8 on 2026-06-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_franchise_created_at_franchise_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
